# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'iTunesWishList'
  app.device_family = [:ipad]
  app.info_plist['UILaunchImageFile'] = 'launch'
  app.identifier = "com.wisdomgroup." + app.name
end
